apiVersion: skaffold/v1beta10
kind: Config

profiles:
  - name: staging-dev
    deploy:
      kustomize:
        path: "./kustomize/overlays/staging-dev"
  # `export SKAFFOLD_PROFILE=local` in your environment for any local overrides
  - name: local
    activation:
      - kubeContext: local
    deploy:
      kustomize:
        path: "./kustomize/overlays/local"

build:
  local:
    useBuildkit: true

  artifacts:
    - image: replicated-install-scripts
      context: "."
      docker:
        dockerfile: ./Dockerfile.skaffold

deploy:
  kustomize:
    path: "./kustomize/overlays/dev"
