---
version: '3.3'
services:
  ship:
    image: replicated/ship:alpha
    volumes:
        - $PWD:/out
        - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --customer-id={{ customer_id }}{% if replicated_prem_graphql_endpoint != 'https://pg.replicated.com/graphql' %}
      - --customer-endpoint={{ replicated_prem_graphql_endpoint }}
{%- endif %}
      - --log-level={{ log_level }}
    ports:
      - 8880:8880

  console:
    image: replicated/ship-console:alpha
    ports:
      - 8025:80
