---
version: '3.3'
services:
  ship:
    image: replicated/ship:alpha
    volumes:
        - $PWD:/out
        - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --customer-id=$CUSTOMER_ID
      - --customer-endpoint=$CUSTOMER_ENDPOINT
      - --log-level=$LOG_LEVEL
    ports:
      - 8880:8880

  console:
    image: replicated/ship-console:alpha
    ports:
      - 8800:80
