
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: install-scripts
spec:
  template:
    metadata:
      labels:
        app: install-scripts
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - install-scripts
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: install-scripts
          image: replicated/install-scripts
          imagePullPolicy: IfNotPresent
          ports:
            - name: install-scripts
              containerPort: 5000