apiVersion: v1
kind: Service
metadata:
  name: install-scripts
  labels:
    app: install-scripts
spec:
  type: LoadBalancer
  ports:
    - name: install-scripts
      port: 8090
      targetPort: install-scripts
  selector:
    app: install-scripts